/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch02_project_ProjectActivity */

#ifndef _Included_ch02_project_ProjectActivity
#define _Included_ch02_project_ProjectActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch02_project_ProjectActivity
 * Method:    getMyData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch02_project_ProjectActivity_getMyData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
