/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opengl_shader_ViewRenderer */

#ifndef _Included_com_opengl_shader_ViewRenderer
#define _Included_com_opengl_shader_ViewRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opengl_shader_ViewRenderer
 * Method:    initialize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_opengl_shader_ViewRenderer_initialize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_opengl_shader_ViewRenderer
 * Method:    drawFrame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_opengl_shader_ViewRenderer_drawFrame
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
